apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "${ADVERTISE_ADDRESS}:6443"
networking:
  podSubnet: "${POD_NETWORK_CIDR}"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "${ADVERTISE_ADDRESS}"
  bindPort: 6443
nodeRegistration:
    kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/master="
